/******************************************************************************
 * The contents of this file are subject to the   Compiere License  Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * You may obtain a copy of the License at http://www.compiere.org/license.html
 * Software distributed under the License is distributed on an  "AS IS"  basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific language governing rights and limitations under the License.
 * The Original Code is Compiere ERP & CRM Smart Business Solution. The Initial
 * Developer of the Original Code is Jorg Janke. Portions created by Jorg Janke
 * are Copyright (C) 1999-2005 Jorg Janke.
 * All parts are Copyright (C) 1999-2005 ComPiere, Inc.  All Rights Reserved.
 * Contributor(s): ______________________________________.
 *****************************************************************************/
package compiere.model;

import java.sql.*;
import java.util.*;

import org.compiere.model.*;


/**
 *	This is a non-working example of a Persistent Business Object.
 *	You would extend the class generated by GenerateModel.java
 *	
 *  @author Jorg Janke
 *  @version $Id: MyModelExample.java,v 1.5 2005/12/23 01:45:47 jjanke Exp $
 */
public class MyModelExample extends PO
{
	/**
	 * 	Standard constructor.
	 * 	You must implement this constructor for Compiere Persistency
	 *	@param ctx context
	 *	@param ID the primary key ID
	 */
	public MyModelExample (Properties ctx, int ID, String trxName)
	{
		super (ctx, ID, trxName);
	}	//	MyModelExample

	/**
	 * 	Optional Load Constructor.
	 * 	You would use this constructor to load several business objects.
	 *  <code>
	 * 	SELECT * FROM MyModelExample WHERE ...
	 *  </code> 
	 *  @param ctx context
	 *  @param rs result set
	 */
	public MyModelExample (Properties ctx, ResultSet rs, String trxName)
	{
		super (ctx, rs, trxName);
	}	//	MyModelExample

	
	
	/**
	 * 	Init Persistent Object.
	 * 	You would NOT create this method as it is created by the persistency
	 * 	class generated by GenerateModel.java
	 *	@param ctx	context
	 *	@return PO information
	 */
	protected POInfo initPO (Properties ctx)
	{
		return null;
	}	//	initPO

	/**
	 * 	Get Access Level
	 *	@return access level
	 */
	protected int get_AccessLevel()
	{
		return 0;
	}	//	get_AccessLevel
	
}	//	MyModelExample
