SELECT
obl.AD_Client_ID ,
obl.AD_Org_ID ,
obl.CreatedBy ,
obl.UpdatedBY ,
obl.Updated ,
obl.Created ,
obl.IsActive ,
obl.MPC_Order_BOM_ID,
obl.MPC_Order_BOMLine_ID  ,
obl.MPC_Order_ID ,
obl.IsCritical ,
obl.M_Product_ID  ,
(Select p.Name FROM M_Product p Where p.M_Product_ID=o.M_Product_ID) as Name,
obl.C_UOM_ID  ,
CASE  WHEN s.QtyOnhand IS  NULL THEN 0 ELSE s.QtyOnhand END AS QtyOnhand,
ROUND(obl.QtyRequiered ,4) AS QtyRequiered ,
CASE  WHEN o.QtyBatchs = 0 THEN 1 ELSE ROUND( obl.QtyRequiered / o.QtyBatchs, 4) END AS QtyBatchSize,
ROUND(BOMQtyReserved(obl.M_Product_ID,obl.M_Warehouse_ID,0), 4) AS QtyReserved ,
ROUND(BOMQtyAvailable(obl.M_Product_ID,obl.M_Warehouse_ID,0),4) AS QtyAvailable ,
obl.M_Warehouse_ID  ,
obl.QtyBom ,
obl.isQtyPercentage ,
ROUND(obl.QtyBatch,4) AS QtyBatch ,
l.M_Locator_ID ,
s.m_attributesetinstance_id, 
l.x ,
l.y ,
l.z 
FROM MPC_Order_BOMLine obl INNER JOIN MPC_Order o ON (o.MPC_Order_ID = obl.MPC_Order_ID)  LEFT OUTER  JOIN M_Storage s ON ( s.M_Product_ID = obl.M_Product_ID AND s.QtyOnHand <> 0 AND  obl.M_Warehouse_ID = (SELECT ld.M_Warehouse_ID FROM M_Locator ld WHERE  s.M_Locator_ID=ld.M_Locator_ID))   LEFT OUTER JOIN M_Locator l ON (l.M_Locator_ID =  s.M_Locator_ID)  ORDER BY obl.M_Product_ID 
;