package org.zynnia.cot.interfaces;

import org.zynnia.cot.model.CotFooter;
import org.zynnia.cot.model.CotHeader;
import org.zynnia.cot.model.CotShipping;

/**
 *
 * @author alejandro
 */
public interface ICotGenerator {
    /**
     * Add shipment to generator for send to ARBA.
     *
     * @param shipping the shipping to be sent to ARBA
     * @throws IllegalArgumentException if the shipping is null.
     * @see CotShipping
     */
    void addShipping(CotShipping shipping);

    /**
     * Return the COT code generated by ARBA for shipping added.
     *
     * @return COT code generated
     */
    String getCotCode();

    /**
     * Return the footer of the data send to ARBA.
     *
     * @return header with organizaton data
     * @see CotFooter
     */
    CotFooter getFooter();

    /**
     * Return the header of the data send to ARBA.
     *
     * @return header with organizaton data
     * @see CotHeader
     */
    CotHeader getHeader();

    /**
     * Sets the header to be sent to ARBA.
     *
     * @param footer the footer with products summary
     */
    void setFooter(CotFooter footer);

    /**
     * Sets the header to be sent to ARBA.
     *
     * @param header the header with organizaton data
     */
    void setHeader(CotHeader header);
}
