CREATE TABLE "COMPIERE"."C_CREDITCARD"
  (
    "C_CREDITCARD_ID" NUMBER(10,0) NOT NULL ENABLE,
    "AD_CLIENT_ID"     NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"        NUMBER(10,0) NOT NULL ENABLE,
    "ISACTIVE"         CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"       NUMBER(10,0) NOT NULL ENABLE,
    "C_BANK_ID"       NUMBER(10,0) NOT NULL ENABLE,
    "NAME" NVARCHAR2(255),
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "C_CREDITCARD_KEY" PRIMARY KEY ("C_CREDITCARD_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "CBANK_CCREDITCARD" FOREIGN KEY ("C_BANK_ID") REFERENCES "COMPIERE"."C_BANK" ("C_BANK_ID") ON
  DELETE CASCADE DISABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE TABLE "COMPIERE"."C_CREDITCARD_ACCT"
  (
    "C_CREDITCARD_ID" NUMBER(10,0) NOT NULL ENABLE,
    "C_ACCTSCHEMA_ID"  NUMBER(10,0) NOT NULL ENABLE,
    "AD_CLIENT_ID"     NUMBER(10,0) NOT NULL ENABLE,
    "AD_ORG_ID"        NUMBER(10,0) NOT NULL ENABLE,
    "ISACTIVE"         CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    "CREATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATEDBY" NUMBER(10,0) NOT NULL ENABLE,
    "UPDATED" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "UPDATEDBY"              NUMBER(10,0) NOT NULL ENABLE,
    "C_TAR_ACCT"       NUMBER(10,0) NOT NULL ENABLE,
    CHECK (IsActive IN ('Y','N')) ENABLE,
    CONSTRAINT "C_CREDITCARD_ACCT_KEY" PRIMARY KEY ("C_CREDITCARD_ID", "C_ACCTSCHEMA_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "C_TAR_ACCT_FK" FOREIGN KEY ("C_ACCTSCHEMA_ID") REFERENCES "COMPIERE"."C_ACCTSCHEMA" ("C_ACCTSCHEMA_ID") ON
  DELETE CASCADE DISABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

ALTER TABLE "COMPIERE"."C_VALORPAGO" ADD (C_CREDITCARD_ID NUMBER(10,0));

--------------------------------------------------------------------------------
--      ERP - Reintegro de Exportacion
--------------------------------------------------------------------------------

/*
        hay que agregar una sequencia para que autoincremente el documentno
*/

-- obtengo el prox id 
SELECT MAX(ad_sequence_id)+1 FROM ad_sequence;

-- inserto con ese id
Insert into AD_SEQUENCE 
(AD_SEQUENCE_ID,AD_CLIENT_ID,AD_ORG_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,DESCRIPTION,VFORMAT,ISAUTOSEQUENCE,INCREMENTNO,STARTNO,CURRENTNEXT,CURRENTNEXTSYS,ISAUDITED,ISTABLEID,PREFIX,SUFFIX,STARTNEWYEAR) 
values 
(5000018,1000002,0,'Y',to_date('04/11/2009','DD/MM/RRRR'),1000684,to_date('04/11/2011','DD/MM/RRRR'),1000684,'MV Reintegro de Exportación',null,null,'Y',1,1000000,1,100,'N','N',null,null,'N');

/*
    hay q insertar un nuevo doctype
*/
-- verifico los tipos de documentos existentes
select * from c_doctype;

-- Verifico los tipos de document q existen para movimientos de fondos
select * from c_doctype where c_doctype_id IN (
  select distinct c_doctype_id from c_movimientofondos 
);

-- chekeo q no exista el par de secuencia - tipo de documento
SELECT dt.C_DocType_ID, sq.CurrentNext
FROM C_DocType dt LEFT JOIN AD_SEQUENCE sq ON (dt.DocNoSequence_ID = sq.AD_Sequence_ID)
WHERE PrintName = 'MVF R';

-- Seobtine el valor para el siguiente tipo de documento
select max(c_doctype_id) from c_doctype;

-- insert el tipo de document
Insert into c_doctype(C_DOCTYPE_ID,AD_CLIENT_ID,AD_ORG_ID,ISACTIVE,CREATED,CREATEDBY,UPDATED,UPDATEDBY,NAME,PRINTNAME,DESCRIPTION,DOCBASETYPE,ISSOTRX,DOCSUBTYPESO,HASPROFORMA,C_DOCTYPEPROFORMA_ID,C_DOCTYPESHIPMENT_ID,C_DOCTYPEINVOICE_ID,ISDOCNOCONTROLLED,DOCNOSEQUENCE_ID,GL_CATEGORY_ID,HASCHARGES,DOCUMENTNOTE,ISDEFAULT,DOCUMENTCOPIES,AD_PRINTFORMAT_ID,ISDEFAULTCOUNTERDOC,ISSHIPCONFIRM,ISPICKQACONFIRM,ISINTRANSIT,ISSPLITWHENDIFFERENCE,C_DOCTYPEDIFFERENCE_ID,ISCREATECOUNTER,C_REVDOCTYPE_ID) 
values 
(5000016,1000002,0,'Y',to_date('05/03/2010','DD/MM/RRRR'),1000684,to_date('05/03/2010','DD/MM/RRRR'),1000684,'Reintegro de Exportación','MVF R',null,'AMM','N',null,'N',null,null,null,'Y',5000018,1000021,'N',null,'N',1,null,'N','N','N','N','N',null,'Y',null);

-- chekeo q ahora si exista el par tipo de doc, secuencia
SELECT dt.C_DocType_ID, sq.CurrentNext
FROM C_DocType dt LEFT JOIN AD_SEQUENCE sq ON (dt.DocNoSequence_ID = sq.AD_Sequence_ID)
WHERE PrintName = 'MVF R';

-- confirmo los cambios
commit;

-- verifico si estan los hechos contables dados de alta
-- NOTA: cambiar Record_ID por uno existente
SELECT * FROM Fact_Acct WHERE Record_ID=5000609 AND AD_Table_ID=1000304;

-- Update model validator for PAnAdmin
UPDATE "COMPIERE"."AD_CLIENT" SET modelvalidationclasses = 'org.zynnia.model.AutomaticPaymentFromInvoice' WHERE NAME = 'Panalab - En Desarrollo' ;

-- Modificacion AMPLIACION SUSS
ALTER TABLE "COMPIERE"."C_BPartner" ADD (SUSS_PERCENTAGE NUMBER(10,0));

